version: "2"
services:

  vertcoind-main:
    image: firrae/vertcoind
    restart: always
    expose:
      - "8332"
      - "8333"
    ports:
      - "5889:5889"
    volumes:
      - ./data/vtc/main/coind:/data
    command: -rpcuser=middleware -rpcpassword=middleware -rpcallowip=0.0.0.0/0 -rpcport=8332 -txindex

  vtc-middleware-cpp-main:
    image: blkidx
    restart: always
    environment:
      - COIND_HOST=vertcoind-main
    expose:
      - "8888"
    volumes:
      - ./data/vtc/main/coind/blocks:/blocks
      - ./data/vtc/main/index:/index
      - ./coins:/coins
    command: --coinParams=/coins/vertcoin-mainnet.json

networks:    
  default:
    external:
      name: blockchain-indexer
